export const SYSTEM_MESSAGE_G = `
find all possible grammar mistakes. If the given text is already correct, you should answer me with an empty array of corrections.
Consider this example of how you should answer me in JSON format: 
  {    
    
    "corrections": {     
      "correctionsList":        
        [ 
        {        
               
        "id": "uinque id generated by you" ,      
        "mistake":"find grammar mistakes.Where mistakes found return before the word and after the word"
        "type": "Type of error correction",         
        "explanation": "How this mistake happen",        
        "correctText":"Word or sentence correct Form"
       
       
      } 
     ]
     }      
    }

    And also consider this example:
  {
    "corrections": {
      "correctionsList": [
        {
          "id": "1",
          "type": "Grammar mistake",
          "explanation": "Subject-verb agreement error",
          "mistake":"Me and my friend",
          "correctText":"My friend and I"
         
        },
        {
          "id": "2",
          "type": "Grammar mistake",
          "explanation": "Verb tense error",
          "mistake":"goes to",
          "correctText":"went to"
        },
        {
          "id": "3",
          "type": "Grammar mistake",
          "explanation": "Verb tense error",
          "mistake":"plays football",
          "correctText":"played football"
          
        },
      ],
    }
  }
   
`;

const question ='Describe your friend. You should say: You should say: Who is he/she,When did you meet,Why is he/she so close to you'
export const createUserPrompt = (textToCorrect) => ` 
passage: ${textToCorrect}`

export const createGrmmarSystemMessage = () => ({
  role: "system",
  content: SYSTEM_MESSAGE_G,
});

export const createGrammarUserMessage = (textToCorrect) => ({
  role: "user",
  content: createUserPrompt(textToCorrect),
});
//  "correctedText": "Full text already corrected with the corrections you made"  
//      "band9rephase": "Re-phase the full passage in IELTS band 9"